import { StyleSheet } from 'react-native';

const userProfileStyles = StyleSheet.create({
    backgroundContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 0,
    },
    circle: {
        position: 'absolute',
        backgroundColor: 'rgba(255, 0, 0, 1)',
        borderRadius: 50,
        width: 100,
        height: 100,
    },
    circle1: {
        top: 100,
        right: -10,
        backgroundColor: '#FFBA00',
    },
    circle2: {
        top: 150,
        right: -40,
        backgroundColor: '#0C3B2E',
    },
    circle4: {
        top: 400,
        left: -10,
        backgroundColor: '#0C3B2E',
    },
    circle3: {
        top: 350,
        left: -30,
        backgroundColor: '#FFBA00',
    },
    circle5: {
        bottom: 300,
        right: -50,
        backgroundColor: '#0C3B2E',
        height: 180,
        width: 180,
        borderRadius: 140,
    },
    circle6: {
        bottom: 100,
        left: -70,
        backgroundColor: '#FFBA00',
        height: 180,
        width: 180,
        borderRadius: 140,
    },
    editProfileContainer: {
        borderRadius: 20,
        padding: 20,
        width: '100%',
        marginTop: 0,
    },
    profilePic: {
        width: 150,
        height: 150,
        borderRadius: 75,
        marginBottom: 10,
        alignSelf: 'center',
    },
    statusText: {
        fontSize: 16,
        marginBottom: 15,
        textAlign: 'center',
        fontFamily: 'Poppins_400Regular',
    },
    label: {
        fontSize: 15,
        marginBottom: 0,
        fontFamily: 'Poppins_400Regular',
        marginLeft: 10,
        color: '#0C3B2E',
    },
    input: {
        width: '100%',
        height: 56,
        borderWidth: 0,
        marginBottom: 15,
        padding: 10,
        fontSize: 16,
        borderRadius: 14,
        backgroundColor: 'white',
        textAlign: 'left',
        justifyContent: 'center',
        fontFamily: 'Poppins_400Regular',
    },
    changeButton: {
        width: 167,
        marginVertical: 30,
        fontSize: 25,
        alignSelf: 'center',
    },
    name: {
        fontSize: 23,
        marginBottom: 0,
        color: '#0C3B2E',
        fontFamily: "Poppins_700Bold",
        height: 35,
        textAlign: 'center',
    },
    emailInput: {
        width: '100%',
        height: 56,
        borderWidth: 0,
        marginBottom: 15,
        padding: 10,
        fontSize: 16,
        borderRadius: 14,
        backgroundColor: 'white',
        textAlign: 'left',
        justifyContent: 'center',
        fontFamily: 'Poppins_400Regular',
        color: 'black',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        position: 'relative',
        marginTop: 0,
    },

    screenTitle: {
        fontSize: 30,
        fontFamily: 'Poppins_600SemiBold',
        textAlign: 'center',
        flex: 1,
    },

    goBackButton: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 24,
        position: 'absolute',
        left: 0,
        zIndex: 1,
    },
});

export default userProfileStyles;
